on:
  push:
    tags:
    - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip install --user poetry
          python -m poetry install --no-dev --no-root -E pyinstaller
          python -m poetry run python -OO -m PyInstaller --onefile minecli/minecli.py
          mv dist/minecli dist/minecli-linux
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          artifacts: ./dist/minecli-linux
          token: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip install --user poetry
          python -m poetry install --no-dev --no-root -E pyinstaller
          python -m poetry run python -OO -m PyInstaller --onefile minecli/minecli.py
          Rename-Item -Path "dist\minecli.exe" -NewName "minecli-windows.exe"
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          artifacts: ./dist/minecli-windows.exe
          token: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip install --user poetry
          python -m poetry install --no-dev --no-root -E pyinstaller
          python -m poetry run python -OO -m PyInstaller --onefile minecli/minecli.py
          mv dist/minecli dist/minecli-macos
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          artifacts: ./dist/minecli-macos
          token: ${{ secrets.GITHUB_TOKEN }}
