on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip install --user poetry
          python -m poetry install --no-dev --no-root -E pyinstaller
          python -m poetry run python -OO -m PyInstaller --onefile -n "minecli-${{ matrix.os }}" minecli/minecli.py
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          artifacts: ./dist/minecli-${{ matrix.os }}*
          token: ${{ secrets.GITHUB_TOKEN }}
